/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package North_South_University;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author Farid
 */
public class Attendances_Math extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Institute
     */
    public Attendances_Math() {
        initComponents();
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        setLocationRelativeTo(null);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        attendance();

        ImageIcon icon = new ImageIcon("image\\\\nsu-logo.png");
        Image a = icon.getImage();
        this.setIconImage(a);
        this.setTitle("North Shouth University mangement");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desgin image/nsu-logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1978, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1305, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "Agust", "Septembor", "Octobar", "November", "December" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jComboBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int r = 0;

    JComboBox jcombo[];
    JButton button[];
    JTextField txt[];
    JLabel label[];
    JLabel label2[];
    Connection con;

    void attendance() {
        Connection con = new DB().getConnect();
        try {
            PreparedStatement st = con.prepareStatement("select * from students where Department='Math'");
            ResultSet r3 = st.executeQuery();
            int a = 0;
            while (r3.next()) {
                r++;

            }

        } catch (SQLException ex) {

        }

        jcombo = new JComboBox[r];
        button = new JButton[r];
        txt = new JTextField[r];

        label = new JLabel[r * 3];
        label2 = new JLabel[4];

        int i = 0;
        int c = 0;
        int x = 10;
        int y = 10;

        int x1 = 130;
        int y1 = 10;

        int x2 = 340;
        int y2 = 10;

        int x3 = 520;
        int y3 = 10;

        int x4 = 360;
        int y4 = 10;

        try {
            con = new DB().getConnect();
            PreparedStatement stm = con.prepareStatement("select * from students where department='Math'");
            ResultSet rs = stm.executeQuery();
            // ResultSetMetaData r = stm.getMetaData();
            javax.swing.border.Border border = BorderFactory.createLineBorder(Color.gray, 2);
            label2[0] = new JLabel("ID");
            label2[0].setBounds(10, 10, 100, 20);
            label2[0].setVisible(true);
            label2[0].setBorder(border);
            label2[0].setHorizontalAlignment(SwingConstants.CENTER);
            label2[0].setVerticalAlignment(SwingConstants.CENTER);
            jPanel2.add(label2[0]);

            label2[1] = new JLabel("Student Name");
            label2[1].setBounds(130, 10, 180, 20);
            label2[1].setVisible(true);
            label2[1].setBorder(border);
            label2[1].setHorizontalAlignment(SwingConstants.CENTER);
            label2[1].setVerticalAlignment(SwingConstants.CENTER);
            jPanel2.add(label2[1]);

            label2[2] = new JLabel("Department");
            label2[2].setBounds(340, 10, 150, 20);
            label2[2].setVisible(true);
            label2[2].setBorder(border);
            label2[2].setHorizontalAlignment(SwingConstants.CENTER);
            label2[2].setVerticalAlignment(SwingConstants.CENTER);
            jPanel2.add(label2[2]);

//            label2[3] = new JLabel("Status");
//            label2[3].setBounds(520, 10, 150, 20);
//            label2[3].setVisible(true);
//            label2[3].setBorder(border);
//            label2[3].setHorizontalAlignment(SwingConstants.CENTER);
//            label2[3].setVerticalAlignment(SwingConstants.CENTER);
//            jPanel2.add(label2[3]);
            while (rs.next()) {
                y += 30;
                y1 += 30;
                y2 += 30;
                y3 += 30;
                y4 += 45;

                label[i] = new JLabel(rs.getString(1));
                label[i].setBounds(x, y, 100, 20);
                label[i].setVisible(true);
                label[i].setBorder(border);
                label[i].setHorizontalAlignment(SwingConstants.CENTER);
                label[i].setVerticalAlignment(SwingConstants.CENTER);
                jPanel2.add(label[i]);
                i++;
                label[i] = new JLabel(rs.getString(2));
                label[i].setBounds(x1, y1, 180, 20);
                label[i].setVisible(true);
                label[i].setBorder(border);
                label[i].setHorizontalAlignment(SwingConstants.CENTER);
                label[i].setVerticalAlignment(SwingConstants.CENTER);
                jPanel2.add(label[i]);
                i++;
                label[i] = new JLabel(rs.getString(8));
                label[i].setBounds(x2, y2, 150, 20);
                label[i].setVisible(true);
                label[i].setBorder(border);
                label[i].setHorizontalAlignment(SwingConstants.CENTER);
                label[i].setVerticalAlignment(SwingConstants.CENTER);
                jPanel2.add(label[i]);
                //System.out.println(i);

//                jcombo[c] = new JComboBox();
//                jcombo[c].addItem("Present");
//                jcombo[c].addItem("Absent");
//                jcombo[c].addItem("Late");
//
//                jcombo[c].setBounds(x3, y3, 150, 20);
//                jPanel2.add(jcombo[c]);
//                c++;
                i++;
            }
            button[0] = new JButton();
            button[0].setBounds(x4, y4, 100, 30);
            button[0].setText("Save");
            button[0].setVisible(true);
            button[0].addActionListener(this);
            jPanel2.add(button[0]);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated


    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Institute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Institute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Institute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Institute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendances_Math().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {

        if (e.getSource().equals(button[0])) {

            try {
                Connection con = new DB().getConnect();

                PreparedStatement stm = con.prepareStatement("insert into math_attendances values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                PreparedStatement stm2 = con.prepareStatement("select * from math_attendances where Month='" + (String) jComboBox1.getSelectedItem() + "'");
                ResultSet rs = stm2.executeQuery();
                if (rs.next()) {

                    if (!jComboBox1.getSelectedItem().equals(rs.getString(4))) {
                        int a = 0;
                        int b = 0;
                        int c = 3;
                        int x = 0;
                        for (int i = 0; i < label.length; i++) {

                            if (c == ++b) {
                                //System.out.println(i);
                                stm.setString(1, label[i - 2].getText());
                                stm.setString(2, label[i - 1].getText());
                                stm.setString(3, label[i - 0].getText());
                                stm.setString(4, (String) jComboBox1.getSelectedItem());
                                stm.setString(5, String.valueOf(Integer.parseInt((String) jComboBox2.getSelectedItem())));

                                stm.setString(6, "0");
                                stm.setString(7, "0");
                                stm.setString(8, "0");
                                stm.setString(9, "0");
                                stm.setString(10, "0");

                                stm.setString(11, "0");
                                stm.setString(12, "0");
                                stm.setString(13, "0");
                                stm.setString(14, "0");
                                stm.setString(15, "0");

                                stm.setString(16, "0");
                                stm.setString(17, "0");
                                stm.setString(18, "0");
                                stm.setString(19, "0");
                                stm.setString(20, "0");

                                stm.setString(21, "0");
                                stm.setString(22, "0");
                                stm.setString(23, "0");
                                stm.setString(24, "0");
                                stm.setString(25, "0");

                                stm.setString(26, "0");
                                stm.setString(6, "0");
                                stm.setString(27, "0");
                                stm.setString(28, "0");
                                stm.setString(29, "0");

                                stm.setString(30, "0");
                                stm.setString(31, "0");
                                stm.setString(32, "0");
                                stm.setString(33, "0");
                                stm.setString(34, "0");

                                stm.setString(35, "0");
                                stm.setInt(37, 0);
                                stm.setInt(38, 0);
                                stm.setInt(39, 0);

                                int res = stm.executeUpdate();
                                System.out.println(res);
                                c += 3;
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Duplicate not allow", "Check Duplicate", JOptionPane.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
                    }
                } else {

                    int a = 0;
                    int b = 0;
                    int c = 3;
                    int x = 0;
                    for (int i = 0; i < label.length; i++) {

                        if (c == ++b) {
                            //System.out.println(i);
                            stm.setString(1, label[i - 2].getText());
                            stm.setString(2, label[i - 1].getText());
                            stm.setString(3, label[i - 0].getText());
                            stm.setString(4, (String) jComboBox1.getSelectedItem());
                            stm.setString(5, String.valueOf(Integer.parseInt((String) jComboBox2.getSelectedItem())));

                            stm.setString(6, "0");
                            stm.setString(7, "0");
                            stm.setString(8, "0");
                            stm.setString(9, "0");
                            stm.setString(10, "0");

                            stm.setString(11, "0");
                            stm.setString(12, "0");
                            stm.setString(13, "0");
                            stm.setString(14, "0");
                            stm.setString(15, "0");

                            stm.setString(16, "0");
                            stm.setString(17, "0");
                            stm.setString(18, "0");
                            stm.setString(19, "0");
                            stm.setString(20, "0");

                            stm.setString(21, "0");
                            stm.setString(22, "0");
                            stm.setString(23, "0");
                            stm.setString(24, "0");
                            stm.setString(25, "0");

                            stm.setString(26, "0");
                            stm.setString(27, "0");
                            stm.setString(28, "0");
                            stm.setString(29, "0");
                            stm.setString(30, "0");

                            stm.setString(31, "0");
                            stm.setString(32, "0");
                            stm.setString(33, "0");
                            stm.setString(34, "0");
                            stm.setString(35, "0");

                            stm.setString(36, "0");
                            stm.setInt(37, 0);
                            stm.setInt(38, 0);
                            stm.setInt(39, 0);

                            int res = stm.executeUpdate();
                            System.out.println(res);
                            c += 3;
                        }
                    }

                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
    }

}
