 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package North_South_University;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Farid
 */
public class Test extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
        attendancesShow();
        setLocationRelativeTo(null);
    }
    JButton button[]=new JButton[100];
    JTextField tf[]=new JTextField[100];
    int i=0;
    private void attendancesShow() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/schools", "root", "farid");
            PreparedStatement stm = con.prepareStatement("select * from new_table");
            ResultSet rs = stm.executeQuery();

            int x = 30;
            int y = 0;
            int x1 = 90;
            int y1 = 0;
            int x2 = 220;
            int y2 = 0;
            int x3 = 280;
            int y3 = 0;
            
            while (rs.next()) {
                y += 30;
                y1 += 30;
                y2 += 30;
                y3 += 30;

                JLabel lb = new JLabel();
                this.add(lb);
                lb.setText(rs.getString(2));
                lb.setBounds(x, y, 60, 20);
                lb.setVisible(true);

                JLabel lb2 = new JLabel();
                Date date = new Date();
                int day = date.getDate();
                SimpleDateFormat df = new SimpleDateFormat("YYYY.MM.dd");

                this.add(lb2);
                lb2.setText(df.format(date));
                lb2.setBounds(x1, y1, 80, 20);
                lb2.setVisible(true);

               
                tf[i]=new JTextField("yes");
                tf[i].setBounds(x2, y2, 40, 26);
                tf[i].setVisible(true);
                this.add(tf[i]);
                

                button[i]=new JButton("No");
                button[i].setBounds(x3, y3, 50, 26);
                button[i].setVisible(true);
                button[i].addActionListener(this);
                this.add(button[i]);
               
                i++;//button text incriment
            }

        } catch (ClassNotFoundException ex) {

        } catch (SQLException ex) {

        }

    }

    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(button[0])){
            tf[0].setText("No");
        }
        if(e.getSource().equals(button[1])){
            tf[1].setText("No");
        }
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
